load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["seeds.go"],
    visibility = ["//visibility:public"],
    deps = ["//hostdisco/pkg/seeds:go_default_library"],
)
