steps:
- name: gcr.io/cloud-builders/bazel
  args: ['build', '//cmd/kops']
      
timeout: 1800s
options:
  machineType: N1_HIGHCPU_8

#artifacts:
#  objects:
#    location: gs://$_GCS_LOCATION
#    # Doesn't work - rejects with "did you mean cp -r"
#    paths: [ "artifacts/**" ]
#    # This is evil, and doesn't work - rejected with "contained space"
#    paths: [ "-r artifacts/**" ]
